jane_auto_mapper:
  private: true
  autoregister: true
  mappings:
    - source: App\Entity\Beer
      target: Generated\Model\Beer

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Generated\Normalizer\JaneObjectNormalizer: ~
